version: '3.9'

services:

  mysql8:
    image: mysql:8.0
    container_name: mysql8
    restart: unless-stopped
    tty: true
    ports:
      - "4037:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
  
  phpmyadmin8:
    image: phpmyadmin/phpmyadmin
    container_name: pma8
    links:
      - mysql8
    environment:
      PMA_HOST: mysql8
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 1G
      MEMORY_LIMIT: 1G
    restart: always
    ports:
      - 8082:80